"""Translate Go TUI wizard JSON result into Lobster configuration files.

The Go wizard (and the questionary fallback) both return a dict with this
contract::

    {
        "provider":           str,   # "anthropic"|"bedrock"|"ollama"|"gemini"|"azure"|"openai"|"openrouter"
        "api_key":            str,   # primary API key (empty for Ollama/Bedrock)
        "api_key_secondary":  str,   # secondary key (e.g. AWS secret; empty otherwise)
        "profile":            str,   # "development"|"production"|"performance"|"max"|""
        "agents":             list[str],  # selected agent names
        "ncbi_key":           str,   # optional NCBI API key
        "cloud_key":          str,   # optional Lobster Cloud key
        "ollama_model":       str,   # Ollama model name (empty for non-Ollama)
        "smart_standardization_enabled": bool,  # enable vector-search setup
        "smart_standardization_openai_key": str,  # OpenAI key for embeddings
        "cancelled":          bool,  # True when user pressed Escape / Ctrl-C
    }

``apply_tui_init_result`` writes:

- ``.env`` (or global credentials file in global mode)
- ``.lobster_workspace/provider_config.json``
- ``.lobster_workspace/agent_config.json``

It intentionally reuses the same helpers that ``init_impl()`` uses so that
workspace files are byte-for-byte identical regardless of which UI path was
taken.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict

logger = logging.getLogger(__name__)

# Map provider name -> env-var key(s) built by the Go wizard / questionary
_PROVIDER_ENV_KEYS: Dict[str, list[str]] = {
    "anthropic": ["ANTHROPIC_API_KEY"],
    "bedrock": ["AWS_BEDROCK_ACCESS_KEY", "AWS_BEDROCK_SECRET_ACCESS_KEY"],
    "ollama": [],  # no API keys
    "gemini": ["GOOGLE_API_KEY"],
    "azure": ["AZURE_AI_ENDPOINT", "AZURE_AI_CREDENTIAL"],
    "openai": ["OPENAI_API_KEY"],
    "openrouter": ["OPENROUTER_API_KEY"],
    "omics-os": ["OMICS_OS_API_KEY"],
}

# Providers that support the LOBSTER_PROFILE env var
_PROFILE_PROVIDERS = {"anthropic", "bedrock"}


def apply_tui_init_result(
    result: Dict[str, Any],
    workspace_path: Path,
    env_path: Path,
    global_config: bool = False,
) -> None:
    """Apply Go TUI (or questionary) wizard results to Lobster config files.

    Args:
        result: Wizard output dict (see module docstring for schema).
        workspace_path: Path to ``.lobster_workspace/`` directory.
        env_path: Path to the ``.env`` file to write.
            Ignored when ``global_config=True``.
        global_config: When True, write global credentials instead of a
            workspace ``.env`` file.

    Raises:
        ValueError: If ``result["provider"]`` is missing or unrecognised.
        IOError: If writing config files fails.
    """
    # ------------------------------------------------------------------
    # Validate required fields
    # ------------------------------------------------------------------
    provider = (result.get("provider") or "").strip().lower()
    if not provider:
        raise ValueError("TUI result is missing 'provider' field")
    if provider not in _PROVIDER_ENV_KEYS:
        raise ValueError(
            f"Unrecognised provider '{provider}' in TUI result. "
            f"Valid: {sorted(_PROVIDER_ENV_KEYS)}"
        )

    api_key = (result.get("api_key") or "").strip()
    api_key_secondary = (result.get("api_key_secondary") or "").strip()
    profile = (result.get("profile") or "").strip()
    agents = result.get("agents") or []
    ncbi_key = (result.get("ncbi_key") or "").strip()
    cloud_key = (result.get("cloud_key") or "").strip()
    ollama_model = (result.get("ollama_model") or "").strip()
    smart_std_enabled = bool(result.get("smart_standardization_enabled"))
    smart_std_openai_key = (
        result.get("smart_standardization_openai_key") or ""
    ).strip()

    from lobster.cli_internal.commands.heavy.init_commands import (
        _normalize_selected_agents,
    )

    agents = _normalize_selected_agents(agents)

    # ------------------------------------------------------------------
    # Build env_lines (same structure as the classic init_impl path)
    # ------------------------------------------------------------------
    env_lines: list[str] = [
        "# Lobster AI Configuration",
        "# Generated by lobster init (TUI wizard)\n",
    ]

    # Primary provider credentials
    if provider == "anthropic":
        if api_key:
            env_lines.append(f"ANTHROPIC_API_KEY={api_key}")

    elif provider == "bedrock":
        if api_key:
            env_lines.append(f"AWS_BEDROCK_ACCESS_KEY={api_key}")
        if api_key_secondary:
            env_lines.append(f"AWS_BEDROCK_SECRET_ACCESS_KEY={api_key_secondary}")

    elif provider == "ollama":
        from lobster.config import provider_setup

        config = provider_setup.create_ollama_config(model_name=ollama_model or None)
        for key, value in config.env_vars.items():
            env_lines.append(f"{key}={value}")

    elif provider == "gemini":
        if api_key:
            env_lines.append(f"GOOGLE_API_KEY={api_key}")

    elif provider == "azure":
        # Go wizard: api_key = credential, api_key_secondary = endpoint URL
        if api_key_secondary:
            env_lines.append(f"AZURE_AI_ENDPOINT={api_key_secondary}")
        if api_key:
            env_lines.append(f"AZURE_AI_CREDENTIAL={api_key}")

    elif provider == "openai":
        if api_key:
            env_lines.append(f"OPENAI_API_KEY={api_key}")

    elif provider == "openrouter":
        if api_key:
            env_lines.append(f"OPENROUTER_API_KEY={api_key}")

    elif provider == "omics-os":
        if api_key:
            env_lines.append(f"OMICS_OS_API_KEY={api_key}")
        # If no api_key, user authenticated via browser (credentials.json)
        env_lines.append("LOBSTER_LLM_PROVIDER=omics-os")

    # Profile (Anthropic / Bedrock only)
    effective_profile = profile if provider in _PROFILE_PROVIDERS else ""
    if not effective_profile and provider in _PROFILE_PROVIDERS:
        effective_profile = "production"  # match classic init default
    if effective_profile:
        env_lines.append("\n# Agent Configuration Profile")
        env_lines.append("# Determines which Claude models are used for analysis")
        env_lines.append(f"LOBSTER_PROFILE={effective_profile}")

    # Optional keys
    if ncbi_key:
        env_lines.append("\n# Optional: Enhanced literature search")
        env_lines.append(f"NCBI_API_KEY={ncbi_key}")

    if cloud_key:
        env_lines.append("\n# Lobster Cloud configuration (enables premium tier)")
        env_lines.append(f"LOBSTER_CLOUD_KEY={cloud_key}")

    if smart_std_enabled:
        embedding_key = smart_std_openai_key
        if provider == "openai" and api_key:
            embedding_key = api_key

        if embedding_key:
            env_lines.append("\n# Smart Standardization / vector search")
            if not (provider == "openai" and embedding_key == api_key):
                env_lines.append(f"OPENAI_API_KEY={embedding_key}")
            env_lines.append("LOBSTER_EMBEDDING_PROVIDER=openai")
        else:
            logger.warning(
                "TUI result enabled Smart Standardization without an OpenAI key; skipping env lines"
            )

    # ------------------------------------------------------------------
    # Build structured config_dict for provider_config.json
    # ------------------------------------------------------------------
    config_dict: Dict[str, Any] = {"provider": provider}
    if effective_profile:
        config_dict["profile"] = effective_profile
    if ollama_model and provider == "ollama":
        config_dict["ollama_model"] = ollama_model

    # Model ID from wizard (applies to all providers)
    model_id = (result.get("model_id") or "").strip()
    if model_id:
        config_dict["model_id"] = model_id

    # ------------------------------------------------------------------
    # Write files
    # ------------------------------------------------------------------
    workspace_path.mkdir(parents=True, exist_ok=True)

    if global_config:
        _write_global(config_dict, env_lines)
    else:
        _write_workspace_env(env_path, env_lines)
        _write_provider_config(config_dict, workspace_path)

    if agents:
        _write_agent_config(agents, workspace_path)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _write_workspace_env(env_path: Path, env_lines: list[str]) -> None:
    """Write the workspace .env file."""
    env_path.parent.mkdir(parents=True, exist_ok=True)
    with open(env_path, "w") as fh:
        fh.write("\n".join(env_lines))
        fh.write("\n")
    logger.info("Wrote workspace .env: %s", env_path)


def _write_provider_config(config_dict: Dict[str, Any], workspace_path: Path) -> None:
    """Write .lobster_workspace/provider_config.json via the shared helper."""
    from lobster.cli_internal.commands.heavy.init_commands import (
        _create_workspace_config,
    )

    _create_workspace_config(config_dict, workspace_path)
    logger.info("Wrote provider_config.json in %s", workspace_path)


def _write_global(config_dict: Dict[str, Any], env_lines: list[str]) -> None:
    """Write global provider config + credentials file."""
    from lobster.cli_internal.commands.heavy.init_commands import _create_global_config

    _create_global_config(config_dict)
    logger.info("Wrote global provider config")

    # Extract credentials from env_lines and save securely
    credentials: Dict[str, str] = {}
    for line in env_lines:
        if "=" in line and not line.startswith("#"):
            key, _, value = line.partition("=")
            key = key.strip()
            if (
                any(
                    tok in key
                    for tok in [
                        "API_KEY",
                        "ACCESS_KEY",
                        "SECRET_KEY",
                        "CLOUD_KEY",
                        "CREDENTIAL",
                    ]
                )
                or key == "LOBSTER_EMBEDDING_PROVIDER"
            ):
                credentials[key] = value.strip()

    if credentials:
        try:
            from lobster.config.global_config import save_global_credentials

            creds_path = save_global_credentials(credentials)
            logger.info("Wrote global credentials: %s", creds_path)
        except Exception as exc:
            logger.warning("Failed to write global credentials: %s", exc)


def _write_agent_config(agents: list[str], workspace_path: Path) -> None:
    """Write .lobster_workspace/agent_config.json via the shared helper."""
    from lobster.cli_internal.commands.heavy.init_commands import _save_agent_config

    _save_agent_config(agents, workspace_path)
    logger.info(
        "Wrote agent_config.json in %s (%d agents)", workspace_path, len(agents)
    )
