#!/usr/bin/env python3
"""
Generate public_allowlist.txt from subscription_tiers.py.

This script ensures a SINGLE SOURCE OF TRUTH for what's free vs premium.
The subscription_tiers.py defines what's available at each tier, and this
script generates the file-level allowlist for syncing to the public repo.

Usage:
    python scripts/generate_allowlist.py                    # Preview changes
    python scripts/generate_allowlist.py --write            # Write allowlist
    python scripts/generate_allowlist.py --validate         # CI validation

Architecture:
    subscription_tiers.py (SOURCE OF TRUTH)
              ↓
    generate_allowlist.py (THIS SCRIPT)
              ↓
    public_allowlist.txt (DERIVED OUTPUT)
"""

import argparse
import sys
from pathlib import Path
from typing import Set

# Add lobster to path for imports
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(REPO_ROOT))

from lobster.config.subscription_tiers import SUBSCRIPTION_TIERS


# =============================================================================
# MAPPING: Agent Names → File Paths
# =============================================================================
# This maps agent registry names to their actual file paths
# Must be kept in sync with config/agent_registry.py

AGENT_FILE_MAPPING = {
    # FREE tier agents
    "research_agent": "lobster/agents/research_agent.py",
    "data_expert_agent": "lobster/agents/data_expert.py",
    "transcriptomics_expert": "lobster/agents/transcriptomics/transcriptomics_expert.py",
    "visualization_expert_agent": "lobster/agents/visualization_expert.py",
    "annotation_expert": "lobster/agents/transcriptomics/annotation_expert.py",
    "de_analysis_expert": "lobster/agents/transcriptomics/de_analysis_expert.py",
    # PREMIUM tier agents
    "metadata_assistant": "lobster/agents/metadata_assistant.py",
    "proteomics_expert": "lobster/agents/proteomics/proteomics_expert.py",
    "machine_learning_expert_agent": "lobster/agents/machine_learning_expert.py",
    "protein_structure_visualization_expert_agent": "lobster/agents/protein_structure_visualization_expert.py",
    # ENTERPRISE agents (loaded via plugin system, not in main repo)
    "custom_feature_agent": "lobster/agents/custom_feature_agent.py",
}

# Services tied to specific agents (premium services for premium agents)
AGENT_SERVICE_DEPENDENCIES = {
    "proteomics_expert": [
        "lobster/services/analysis/proteomics_analysis_service.py",
        "lobster/services/analysis/proteomics_differential_service.py",
        "lobster/services/quality/proteomics_quality_service.py",
        "lobster/services/quality/proteomics_preprocessing_service.py",
        "lobster/services/visualization/proteomics_visualization_service.py",
        "lobster/agents/proteomics/platform_config.py",
        # Proteomics parsers (premium feature)
        "lobster/services/data_access/proteomics_parsers/__init__.py",
        "lobster/services/data_access/proteomics_parsers/base_parser.py",
        "lobster/services/data_access/proteomics_parsers/maxquant_parser.py",
        "lobster/services/data_access/proteomics_parsers/diann_parser.py",
        "lobster/services/data_access/proteomics_parsers/olink_parser.py",
    ],
    "metadata_assistant": [
        "lobster/services/orchestration/publication_processing_service.py",
        "lobster/services/metadata/identifier_provenance_service.py",
        "lobster/services/metadata/microbiome_filtering_service.py",
        "lobster/services/metadata/disease_standardization_service.py",
        "lobster/services/metadata/sample_mapping_service.py",
        "lobster/core/schemas/publication_queue.py",
        "lobster/core/publication_queue.py",
        "lobster/core/ris_parser.py",
    ],
    "custom_feature_agent": [
        "lobster/services/execution/sdk_delegation_service.py",
        "lobster/agents/unified_agent_creation_template.md",
    ],
    "machine_learning_expert_agent": [
        "lobster/services/ml/ml_transcriptomics_service_ALPHA.py",
        "lobster/services/ml/ml_proteomics_service_ALPHA.py",
    ],
}


# =============================================================================
# STATIC ALLOWLIST SECTIONS
# =============================================================================
# These are files that are always included/excluded regardless of tier

ALWAYS_INCLUDED = """
# =============================================================================
# PUBLIC REPOSITORY ALLOWLIST (lobster → lobster-local sync)
# =============================================================================
# AUTO-GENERATED by scripts/generate_allowlist.py
# DO NOT EDIT MANUALLY - Edit subscription_tiers.py instead
#
# Source of Truth: lobster/config/subscription_tiers.py
# Generated: {timestamp}
# =============================================================================


# =============================================================================
# FUNCTIONAL & BUILD FILES
# =============================================================================
verify_installation.py
uv.lock
setup.py
pyproject.toml
main.py

# Installation scripts
dev_install.sh
install-ubuntu.sh
install.bat
install.ps1

# Container files (CLI only)
Dockerfile


# =============================================================================
# DOCUMENTATION
# =============================================================================
README.md
LICENSE
.env.example


# =============================================================================
# DEVELOPMENT FILES
# =============================================================================
.pre-commit-config.yaml
pytest.ini
.gitignore
Makefile


# =============================================================================
# CORE ENGINE (Always Open-Core)
# =============================================================================
lobster/__init__.py
lobster/__main__.py
lobster/_version.py
lobster/version.py
lobster/cli.py
lobster/main.py

# Core infrastructure
lobster/core/__init__.py
lobster/core/client.py
lobster/core/workspace.py
lobster/core/data_manager_v2.py
lobster/core/provenance.py
lobster/core/download_queue.py
lobster/core/queue_storage.py
lobster/core/archive_utils.py
lobster/core/analysis_ir.py
lobster/core/ir_coverage.py
lobster/core/exceptions.py
lobster/core/notebook_executor.py
lobster/core/notebook_exporter.py
lobster/core/notebook_validator.py

# Premium infrastructure (enables plugin system in free tier)
lobster/config/subscription_tiers.py
lobster/core/plugin_loader.py
lobster/core/license_manager.py

# Schemas (data models - open core)
lobster/core/schemas/__init__.py
lobster/core/schemas/transcriptomics.py
lobster/core/schemas/proteomics.py
lobster/core/schemas/metabolomics.py
lobster/core/schemas/metagenomics.py
lobster/core/schemas/protein_structure.py
lobster/core/schemas/database_registry.py
lobster/core/schemas/database_mappings.py
lobster/core/schemas/download_queue.py
lobster/core/schemas/download_urls.py
lobster/core/schemas/export_schemas.py
lobster/core/schemas/sra.py
lobster/core/schemas/validation.py

# Adapters (data loading)
lobster/core/adapters/__init__.py
lobster/core/adapters/base.py
lobster/core/adapters/transcriptomics_adapter.py
lobster/core/adapters/pseudobulk_adapter.py
lobster/core/adapters/protein_structure_adapter.py
lobster/core/adapters/proteomics_adapter.py

# Backends (storage)
lobster/core/backends/__init__.py
lobster/core/backends/base.py
lobster/core/backends/h5ad_backend.py
lobster/core/backends/mudata_backend.py

# Interfaces
lobster/core/interfaces/__init__.py
lobster/core/interfaces/adapter.py
lobster/core/interfaces/backend.py
lobster/core/interfaces/base_client.py
lobster/core/interfaces/download_service.py
lobster/core/interfaces/validator.py

# Identifiers
lobster/core/identifiers/__init__.py
lobster/core/identifiers/accession_resolver.py

# Utils
lobster/core/utils/__init__.py
lobster/core/utils/h5ad_utils.py


# =============================================================================
# CONFIGURATION (Always Open-Core)
# =============================================================================
lobster/config/__init__.py
lobster/config/settings.py
lobster/config/config_manager.py
lobster/config/agent_config.py
lobster/config/agent_registry.py
lobster/config/agent_capabilities.py
lobster/config/llm_factory.py
lobster/config/supervisor_config.py
lobster/config/README_CONFIGURATION.md
lobster/config/README_THINKING.md


# =============================================================================
# AGENT INFRASTRUCTURE (Always Open-Core)
# =============================================================================
lobster/agents/__init__.py
lobster/agents/state.py
lobster/agents/graph.py
lobster/agents/draw_graph.py
lobster/agents/supervisor.py
lobster/agents/data_expert_assistant.py

# LangGraph supervisor
lobster/agents/langgraph_supervisor/__init__.py
lobster/agents/langgraph_supervisor/agent_name.py
lobster/agents/langgraph_supervisor/handoff.py
lobster/agents/langgraph_supervisor/supervisor.py
lobster/agents/langgraph_supervisor/README.md

# Agent archives
lobster/agents/archive/ARCHIVE_NOTICE.md
lobster/agents/archive/research_agent_assistant.py

# Transcriptomics module structure
lobster/agents/transcriptomics/__init__.py
lobster/agents/transcriptomics/state.py
lobster/agents/transcriptomics/shared_tools.py

# Proteomics module structure (just structure, not experts)
lobster/agents/proteomics/__init__.py
lobster/agents/proteomics/state.py


# =============================================================================
# SERVICES - OPEN CORE (Always Included)
# =============================================================================

# Analysis - Open Core
lobster/services/__init__.py
lobster/services/analysis/__init__.py
lobster/services/analysis/clustering_service.py
lobster/services/analysis/enhanced_singlecell_service.py
lobster/services/analysis/scvi_embedding_service.py
lobster/services/analysis/structure_analysis_service.py

# Quality Control - Open Core
lobster/services/quality/__init__.py
lobster/services/quality/quality_service.py
lobster/services/quality/preprocessing_service.py

# Visualization - Open Core
lobster/services/visualization/__init__.py
lobster/services/visualization/visualization_service.py
lobster/services/visualization/pymol_visualization_service.py

# Data Access - Open Core
lobster/services/data_access/__init__.py
lobster/services/data_access/geo_service.py
lobster/services/data_access/geo_download_service.py
lobster/services/data_access/geo_fallback_service.py
lobster/services/data_access/content_access_service.py
lobster/services/data_access/workspace_content_service.py
lobster/services/data_access/protein_structure_fetch_service.py
lobster/services/data_access/docling_service.py
lobster/services/data_access/massive_download_service.py
lobster/services/data_access/pride_download_service.py
lobster/services/data_access/sra_download_service.py

# GEO modular package
lobster/services/data_access/geo/__init__.py
lobster/services/data_access/geo/constants.py
lobster/services/data_access/geo/downloader.py
lobster/services/data_access/geo/facade.py
lobster/services/data_access/geo/parser.py
lobster/services/data_access/geo/strategy.py
lobster/services/data_access/geo/loaders/__init__.py
lobster/services/data_access/geo/loaders/tenx.py
lobster/services/data_access/geo/metadata/__init__.py
lobster/services/data_access/geo/sample/__init__.py
lobster/services/data_access/geo/utils/__init__.py

# Data Management - Open Core
lobster/services/data_management/__init__.py
lobster/services/data_management/modality_management_service.py
lobster/services/data_management/concatenation_service.py

# Metadata - Open Core
lobster/services/metadata/__init__.py
lobster/services/metadata/metadata_standardization_service.py
lobster/services/metadata/metadata_validation_service.py
lobster/services/metadata/manual_annotation_service.py
lobster/services/metadata/sample_grouping_service.py

# Protocol extraction - Open Core
lobster/services/metadata/protocol_extraction/__init__.py
lobster/services/metadata/protocol_extraction/base.py
lobster/services/metadata/protocol_extraction/rnaseq/__init__.py
lobster/services/metadata/protocol_extraction/rnaseq/service.py
lobster/services/metadata/protocol_extraction/rnaseq/details.py
lobster/services/metadata/protocol_extraction/amplicon/__init__.py
lobster/services/metadata/protocol_extraction/amplicon/service.py
lobster/services/metadata/protocol_extraction/amplicon/details.py
lobster/services/metadata/protocol_extraction/amplicon/resources/primers.json
lobster/services/metadata/protocol_extraction/mass_spec/__init__.py
lobster/services/metadata/protocol_extraction/mass_spec/service.py
lobster/services/metadata/protocol_extraction/mass_spec/details.py

# Execution - Open Core
lobster/services/execution/__init__.py
lobster/services/execution/custom_code_execution_service.py
lobster/services/execution/execution_context_builder.py

# ML - Open Core (just init)
lobster/services/ml/__init__.py

# Orchestration - Open Core (just init)
lobster/services/orchestration/__init__.py

# Templates - Open Core
lobster/services/templates/__init__.py
lobster/services/templates/annotation_templates.py


# =============================================================================
# TOOLS & UTILITIES (Always Open-Core)
# =============================================================================
lobster/tools/__init__.py
lobster/tools/download_orchestrator.py
lobster/tools/handoff_tool.py
lobster/tools/enhanced_handoff_tool.py
lobster/tools/expert_handoff_manager.py
lobster/tools/expert_handoff_patterns.py
lobster/tools/workspace_tool.py
lobster/tools/workflow_tracker.py
lobster/tools/gpu_detector.py
lobster/tools/rate_limiter.py
lobster/tools/url_transforms.py
lobster/tools/pipeline_strategy.py
lobster/tools/geo_downloader.py
lobster/tools/geo_parser.py
lobster/tools/docling_service.py.backup

# Providers
lobster/tools/providers/__init__.py
lobster/tools/providers/base_provider.py
lobster/tools/providers/abstract_provider.py
lobster/tools/providers/pubmed_provider.py
lobster/tools/providers/pmc_provider.py
lobster/tools/providers/geo_provider.py
lobster/tools/providers/geo_utils.py
lobster/tools/providers/sra_provider.py
lobster/tools/providers/webpage_provider.py
lobster/tools/providers/biorxiv_medrxiv_provider.py
lobster/tools/providers/biorxiv_medrxiv_config.py
lobster/tools/providers/publication_resolver.py
lobster/tools/providers/provider_registry.py
lobster/tools/providers/ncbi_query_builder.py
lobster/tools/providers/organism_enum.py
lobster/tools/providers/structure_provider.py
lobster/tools/providers/pdb_provider.py
lobster/tools/providers/massive_provider.py

# External provider context
lobster/tools/external_providers_context/chimerax_tut.md

# Tool archives
lobster/tools/archive/MIGRATION_NOTICE.md
lobster/tools/archive/unified_content_service.py
lobster/tools/archive/publication_service.py


# =============================================================================
# UI COMPONENTS (Always Open-Core)
# =============================================================================
lobster/ui/__init__.py
lobster/ui/themes.py
lobster/ui/progress_manager.py
lobster/ui/console_manager.py
lobster/ui/live_dashboard.py
lobster/ui/formatters/__init__.py
lobster/ui/components/__init__.py
lobster/ui/components/file_tree.py
lobster/ui/components/status_display.py
lobster/ui/components/parallel_workers_progress.py
lobster/ui/components/multi_progress.py


# =============================================================================
# UTILITIES (Always Open-Core)
# =============================================================================
lobster/utils/__init__.py
lobster/utils/system.py
lobster/utils/ssl_utils.py
lobster/utils/json_extractor.py
lobster/utils/logger.py
lobster/utils/progress_wrapper.py
lobster/utils/file_naming.py
lobster/utils/file_analyzer.py
lobster/utils/callbacks.py
lobster/utils/error_handlers.py
lobster/utils/deviance.py


# =============================================================================
# CLI INTERNAL (Always Open-Core)
# =============================================================================
lobster/cli_internal/__init__.py
lobster/cli_internal/utils/__init__.py
lobster/cli_internal/utils/path_resolution.py


# =============================================================================
# CLOUD CLIENT (Enables upgrades from free)
# =============================================================================
lobster/lobster_cloud/__init__.py
lobster/lobster_cloud/client.py


"""

ALWAYS_EXCLUDED = """
# =============================================================================
# ALWAYS EXCLUDED (Regardless of Tier)
# =============================================================================

# Server/API code (private infrastructure)
!lobster/api/**
!lobster/core/api_client.py
!lobster/core/websocket*
!lobster/cdk/**
!Dockerfile.server
!docker-compose.yml

# Internal documentation
!CLAUDE.md
!CLAUDE.md.backup
!README_FULL.md
!LOBSTER_PROJECT_SUMMARY_FOR_CLOUD_BACKEND.md
!activate_claude_code.sh
!activate_claude_code_1m.sh
!kevin_notes_completed/**
!kevin_notes/**

# Scripts (sync infrastructure is private)
!scripts/**

# Tests (private)
!tests/**

# Build artifacts
!**/__pycache__/**
!**/*.pyc
!**/*.pyo
!**/*.pyd
!.env
!**/private/**
!**/customer/**
!**/*_secret*
!**/*_private*
!**/results/**
!**/cache/**
!.mplconfig/**

# Alpha features
!*ALPHA.py
!*websocket*.py
!lobster/streamlit_app.py

# Premium tools
!lobster/tools/rate_limiter_arena.py

# Premium extraction cache
!lobster/core/extraction_cache.py

"""


def get_free_tier_agents() -> Set[str]:
    """Get set of agent names available in FREE tier."""
    return set(SUBSCRIPTION_TIERS["free"]["agents"])


def get_premium_only_agents() -> Set[str]:
    """Get agents that are PREMIUM-only (not in FREE tier)."""
    free_agents = get_free_tier_agents()
    premium_agents = set(SUBSCRIPTION_TIERS["premium"]["agents"])
    return premium_agents - free_agents


def generate_agent_section() -> str:
    """Generate the agent files section based on subscription tiers."""
    lines = [
        "",
        "# =============================================================================",
        "# AGENTS - TIER-BASED (Generated from subscription_tiers.py)",
        "# =============================================================================",
        "",
        "# FREE tier agents (included in public package)",
    ]

    free_agents = get_free_tier_agents()
    for agent in sorted(free_agents):
        if agent in AGENT_FILE_MAPPING:
            lines.append(AGENT_FILE_MAPPING[agent])

    lines.append("")
    lines.append("# PREMIUM tier agents (EXCLUDED from public package)")

    premium_only = get_premium_only_agents()
    for agent in sorted(premium_only):
        if agent in AGENT_FILE_MAPPING:
            lines.append(f"!{AGENT_FILE_MAPPING[agent]}")
            # Also exclude dependent services
            if agent in AGENT_SERVICE_DEPENDENCIES:
                for service in AGENT_SERVICE_DEPENDENCIES[agent]:
                    lines.append(f"!{service}")

    # Also exclude custom_feature_agent (enterprise)
    if "custom_feature_agent" in AGENT_FILE_MAPPING:
        lines.append("")
        lines.append("# ENTERPRISE agents (EXCLUDED - loaded via plugin system)")
        lines.append(f"!{AGENT_FILE_MAPPING['custom_feature_agent']}")
        if "custom_feature_agent" in AGENT_SERVICE_DEPENDENCIES:
            for service in AGENT_SERVICE_DEPENDENCIES["custom_feature_agent"]:
                lines.append(f"!{service}")

    return "\n".join(lines)


def generate_allowlist() -> str:
    """Generate the complete allowlist content."""
    from datetime import datetime

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = ALWAYS_INCLUDED.format(timestamp=timestamp)
    content += generate_agent_section()
    content += ALWAYS_EXCLUDED

    return content


def validate_allowlist(current_path: Path) -> bool:
    """Validate current allowlist matches what would be generated."""
    if not current_path.exists():
        print("ERROR: public_allowlist.txt not found")
        return False

    current = current_path.read_text()
    generated = generate_allowlist()

    # Compare non-timestamp lines
    def normalize(text):
        lines = []
        for line in text.strip().split("\n"):
            # Skip timestamp line
            if "Generated:" in line:
                continue
            lines.append(line)
        return "\n".join(lines)

    if normalize(current) != normalize(generated):
        print("ERROR: public_allowlist.txt is out of sync with subscription_tiers.py")
        print("\nTo fix, run:")
        print("  python scripts/generate_allowlist.py --write")
        return False

    print("OK: public_allowlist.txt is in sync with subscription_tiers.py")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate public_allowlist.txt from subscription_tiers.py"
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the generated allowlist to file"
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate current allowlist matches subscription_tiers.py (for CI)"
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="Show diff between current and generated allowlist"
    )

    args = parser.parse_args()

    allowlist_path = SCRIPT_DIR / "public_allowlist.txt"

    if args.validate:
        success = validate_allowlist(allowlist_path)
        sys.exit(0 if success else 1)

    generated = generate_allowlist()

    if args.diff and allowlist_path.exists():
        import difflib
        current = allowlist_path.read_text()
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile="current",
            tofile="generated"
        )
        print("".join(diff))
        return

    if args.write:
        allowlist_path.write_text(generated)
        print(f"Written: {allowlist_path}")

        # Print summary
        free_agents = get_free_tier_agents()
        premium_only = get_premium_only_agents()
        print(f"\nFREE tier agents ({len(free_agents)}): {sorted(free_agents)}")
        print(f"PREMIUM-only agents ({len(premium_only)}): {sorted(premium_only)}")
    else:
        # Preview mode
        print("=" * 70)
        print("PREVIEW - Generated allowlist (use --write to save)")
        print("=" * 70)
        print(generated)
        print("=" * 70)
        print("\nTo write: python scripts/generate_allowlist.py --write")


if __name__ == "__main__":
    main()
